### ISSUE TITLE
[Enhancement] The way to handle extra info from CDP content.

### ISSUE THREAD

**Issue by devblack** [utyfua/automation-extra-interception-proxy#3]
Is possible to implement support to handle CDP?

Example of the issue: https://github.com/Cuadrix/puppeteer-page-proxy/issues/82

**Comment by utyfua** [comment]
I will take a look tomorrow

**Comment by utyfua** [comment]
The Network.requestWillBeSentExtraInfo and Network.responseReceivedExtraInfo events in the Chrome DevTools Protocol (CDP) are designed to provide extra information about network requests and responses, such as additional HTTP headers added by the browser or by extensions.

However, when we are using `page.setRequestInterception(true)`, CDP client is effectively taking over the handling of requests. This includes things like adding and removing headers.

Because the `requestWillBeSentExtraInfo` and `responseReceivedExtraInfo` events are tied to the internal workings of the browser's network handling, they may not be emitted when request interception is turned on. The events are based on the original, unintercepted requests and responses, and therefore may not reflect any changes made during interception.

That's why [automation-extra-interception-proxy](https://github.com/utyfua/automation-extra-interception-proxy) have same issues as [puppeteer-page-proxy](https://github.com/Cuadrix/puppeteer-page-proxy) does.

Unfortunately, at the moment there is no reliable way to implement this fully. The only thing left is to simulate the behavior of these events as much as possible.

I will keep the issue open until a complete solution is found for all problems associated with the absence of these events.

**Comment by utyfua** [comment]
@devblack Lately, I have been using [reqwest-impersonate](https://github.com/0x676e67/reqwest-impersonate).

It is possible to create an adapter for the library. I was using it independently, so I didn't do it.

Do you still need it? Or maybe just a simple wrapper to use reqwest-impersonate from Node.js?

I am not particularly interested in this at the moment, but I can help as much as I can.

**Comment by devblack** [comment]
Hey. I don't need it anymore. But thank you for the reply.
